<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.github.atomfrede</groupId>
    <artifactId>slides-jfn-26-tamboui</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Hey Mr. TamboU(r)Ine man, create a TUI for me</name>
    <description>Slides for my tamboui talk at java forum nord 26</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <asciidoctor.maven.plugin.version>3.0.0</asciidoctor.maven.plugin.version>
        <asciidoctorj.version>3.0.1</asciidoctorj.version>
        <asciidoctorj-reveal.version>5.2.0</asciidoctorj-reveal.version>
        <jruby.version>10.1.1.0</jruby.version>
    </properties>

    <profiles>
        <profile>
            <id>serve</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <defaultGoal>process-resources</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctor-maven-plugin</artifactId>
                        <version>${asciidoctor.maven.plugin.version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>org.jruby</groupId>
                                <artifactId>jruby</artifactId>
                                <version>${jruby.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.asciidoctor</groupId>
                                <artifactId>asciidoctorj</artifactId>
                                <version>${asciidoctorj.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.asciidoctor</groupId>
                                <artifactId>asciidoctorj-revealjs</artifactId>
                                <version>${asciidoctorj-reveal.version}</version>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <id>generate-slides</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>process-asciidoc</goal>
                                </goals>
                                <configuration>
                                    <backend>revealjs</backend>
                                    <requires>
                                        <require>asciidoctor-revealjs</require>
                                    </requires>
                                    <attributes>
                                        <revealjsdir>
                                            _reveal
                                        </revealjsdir>
                                    </attributes>
                                </configuration>
                            </execution>
                            <execution>
                                <id>serve</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>http</goal>
                                </goals>
                                <configuration>
                                    <port>8080</port>
                                    <backend>revealjs</backend>
                                    <requires>
                                        <require>asciidoctor-revealjs</require>
                                    </requires>
                                    <attributes>
                                        <revealjsdir>
                                            reveal
                                        </revealjsdir>
                                    </attributes>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>gh-pages</id>
            <build>
                <defaultGoal>package</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctor-maven-plugin</artifactId>
                        <version>${asciidoctor.maven.plugin.version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>org.jruby</groupId>
                                <artifactId>jruby</artifactId>
                                <version>${jruby.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.asciidoctor</groupId>
                                <artifactId>asciidoctorj</artifactId>
                                <version>${asciidoctorj.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.asciidoctor</groupId>
                                <artifactId>asciidoctorj-revealjs</artifactId>
                                <version>${asciidoctorj-reveal.version}</version>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <id>generate-slides</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>process-asciidoc</goal>
                                </goals>
                                <configuration>
                                    <backend>revealjs</backend>
                                    <requires>
                                        <require>asciidoctor-revealjs</require>
                                    </requires>
                                    <attributes>
                                        <revealjsdir>
                                            reveal
                                        </revealjsdir>
                                    </attributes>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>3.3.1</version>
                        <executions>
                            <execution>
                                <id>copy-slides</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${basedir}/docs</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${basedir}/target/generated-docs</directory>
                                            <includes>
                                                <include>**/*.*</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>